apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    #    network/sourceloop-sanbox: "true"
    io.sourceloop.service: notification-socket-example
  name: notification-socket-example
  namespace: sourceloop-sandbox
spec:
  replicas: 1
  selector:
    matchLabels:
      io.sourceloop.service: notification-socket-example
  template:
    metadata:
      labels:
        io.sourceloop.service: notification-socket-example
    spec:
      containers:
        - env:
            - name: DB_DATABASE
              value: notification_db
            - name: DB_HOST
              value: postgres.sourceloop-sandbox.svc.cluster.local
            - name: DB_PASSWORD
              value: changeme
            - name: DB_PORT
              value: "5432"
            - name: DB_SCHEMA
              value: public
            - name: DB_USER
              value: postgres
            - name: JWT_ISSUER
              value: https://loopback4-microservice-catalog
            - name: JWT_SECRET
              value: i_am_a_strong_secret
            - name: LOG_LEVEL
              value: debug
            - name: NODE_ENV
              value: dev
          image: localhost:32000/notification-socket-example
          name: notification-socket-example
          ports:
            - containerPort: 3000
          resources: { }
      restartPolicy: Always
status: { }
