apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.sourceloop.service: postgres
  name: postgres
  namespace: sourceloop-sandbox
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
