apiVersion: v1
kind: Service
metadata:
  labels:
    io.sourceloop.service: postgres-orchestrator
  name: postgres-orchestrator
  namespace: sourceloop-sandbox
spec:
  ports:
    - name: "5433"
      port: 5433
      targetPort: 5433
  selector:
    io.sourceloop.service: postgres-orchestrator
status:
  loadBalancer: {}
