version: "3.4"

x-auth-variables: &auth-variables
      NODE_ENV: dev
      LOG_LEVEL: debug
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: ${POSTGRES_USER:-postgres}
      DB_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      DB_DATABASE: authentication_db
      DB_SCHEMA: main
      JWT_SECRET: i_am_a_strong_secret
      JWT_ISSUER: https://loopback4-microservice-catalog
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_URL:
      REDIS_PASSWORD:
      REDIS_DB: 0
      USER_TEMP_PASSWORD: tempP@ssw0rd
      GOOGLE_AUTH_URL:
      GOOGLE_AUTH_CLIENT_ID:
      GOOGLE_AUTH_CLIENT_SECRET:
      GOOGLE_AUTH_TOKEN_URL:
      GOOGLE_AUTH_CALLBACK_URL:
      LOCALE: en
      FORGOT_PASSWORD_LINK_EXPIRY:
      KEYCLOAK_HOST: test
      KEYCLOAK_REALM: test
      KEYCLOAK_CLIENT_ID: test
      KEYCLOAK_CLIENT_SECRET: test
      KEYCLOAK_CALLBACK_URL: test
      RATE_LIMITER_WINDOW_MS: 100
      RATE_LIMITER_MAX_REQS: 100
      X_FRAME_OPTIONS: SAMEORIGIN

x-workflow-variables: &workflow-variables
      NODE_ENV: dev
      LOG_LEVEL: debug
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: ${POSTGRES_USER:-postgres}
      DB_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      DB_DATABASE: workflow_db
      DB_SCHEMA: main
      CAMUNDA_URL: http://camunda:8080/engine-rest

x-audit-variables: &audit-variables
      NODE_ENV: dev
      LOG_LEVEL: debug
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: ${POSTGRES_USER:-postgres}
      DB_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      DB_DATABASE: audit_db
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_URL:
      REDIS_PASSWORD: test
      REDIS_DB: 0
      JWT_SECRET: i_am_a_strong_secret
      JWT_ISSUER: https://loopback4-microservice-catalog

x-scheduler-variables: &scheduler-variables
      NODE_ENV: dev
      LOG_LEVEL: debug
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: ${POSTGRES_USER:-postgres}
      DB_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      DB_DATABASE: scheduler_db
      DB_SCHEMA: main
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_URL:
      REDIS_PASSWORD:
      REDIS_DATABASE: 0
      JWT_SECRET: i_am_a_strong_secret
      JWT_ISSUER: https://loopback4-microservice-catalog

x-video-variables: &video-variables
    VONAGE_API_KEY: 0
    VONAGE_API_SECRET: abc
    TIME_TO_START: 10
    DB_HOST: localhpostgresost
    DB_PORT: 5432
    DB_USER: ${POSTGRES_USER:-postgres}
    DB_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
    DB_DATABASE: video_db
    DB_SCHEMA: main
    JWT_SECRET: i_am_a_strong_secret
    JWT_ISSUER: https://loopback4-microservice-catalog

x-in-mail-variables: &in-mail-variables
      NODE_ENV: dev
      LOG_LEVEL: debug
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: ${POSTGRES_USER:-postgres}
      DB_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      DB_DATABASE: in_mail_db
      DB_SCHEMA: main
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_URL:
      REDIS_PASSWORD:
      REDIS_DATABASE: 0
      JWT_SECRET: i_am_a_strong_secret
      JWT_ISSUER: https://loopback4-microservice-catalog

services:
  auth-multitenant-example:
    image: ${REGISTRY:-localhost:32000}/auth-multitenant-example
    build:
      context: ./auth-multitenant-example
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - sandbox
    environment: *auth-variables
    depends_on:
      - postgres
      - redis
      - postgres_orchestrator
      - auth-multitenant-migration
    restart: on-failure

  auth-multitenant-migration:
    image: ${REGISTRY:-localhost:32000}/auth-multitenant-example
    build:
      context: ./auth-multitenant-example
      dockerfile: Dockerfile
    command: sh -c "sleep 60 && npm run db:migrate"
    environment: *auth-variables
    depends_on:
      - postgres
      - postgres_orchestrator
    networks:
      - sandbox
    restart: on-failure

  notification-socket-example:
    image: ${REGISTRY:-localhost:32000}/notification-socket-example
    build:
      context: ./notification-socket-example
      dockerfile: Dockerfile
    ports:
      - "3030:3000"
    networks:
      - sandbox
    environment:
      NODE_ENV: dev
      LOG_LEVEL: debug
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: ${POSTGRES_USER:-postgres}
      DB_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      DB_DATABASE: notification_db
      DB_SCHEMA: public
      JWT_SECRET: i_am_a_strong_secret
      JWT_ISSUER: https://loopback4-microservice-catalog
    depends_on:
      - postgres

  workflow-ms-example:
    image: ${REGISTRY:-localhost:32000}/workflow-ms-example
    build:
      context: ./workflow-ms-example
      dockerfile: Dockerfile
      args:
          - WORKFLOW_MIGRATION_SKIP=true
    ports:
      - "3031:3000"
    networks:
      - sandbox
    environment: *workflow-variables
    depends_on:
      - postgres
      - camunda
      - postgres_orchestrator
      - workflow-migration
    restart: on-failure

  workflow-migration:
    image: ${REGISTRY:-localhost:32000}/workflow-ms-example
    build:
      context: ./workflow-ms-example
      dockerfile: Dockerfile
    command: sh -c "sleep 60 && npm run db:migrate"
    environment: *workflow-variables
    depends_on:
      - postgres
      - postgres_orchestrator
    networks:
      - sandbox
    restart: on-failure

  audit-ms-example:
    image: ${REGISTRY:-localhost:32000}/audit-ms-example
    build:
      context: ./audit-ms-example
      dockerfile: Dockerfile
    ports:
      - "3032:3000"
    networks:
      - sandbox
    environment: *audit-variables
    depends_on:
      - postgres
      - postgres_orchestrator
      - audit-ms-migration
    restart: on-failure

  audit-ms-migration:
    image: ${REGISTRY:-localhost:32000}/audit-ms-example
    command: sh -c "sleep 60 && npm run db:migrate"
    build:
      context: ./audit-ms-example
      dockerfile: Dockerfile
    environment: *audit-variables
    depends_on:
      - postgres
      - postgres_orchestrator
    networks:
      - sandbox
    restart: on-failure

  scheduler-example:
    image: ${REGISTRY:-localhost:32000}/scheduler-example
    build:
      context: ./scheduler-example
      dockerfile: Dockerfile
    ports:
      - "3034:3000"
    networks:
      - sandbox
    environment: *scheduler-variables
    depends_on:
      - postgres
      - postgres_orchestrator
    restart: on-failure

  video-conferencing-ms-example:
    image: ${REGISTRY:-localhost:32000}/video-conferencing-ms-example
    build:
      context: ./video-conferencing-ms-example
      dockerfile: Dockerfile
    ports:
      - "3040:3000"
    networks:
      - sandbox
    environment: *video-variables
    depends_on:
      - postgres
      - postgres_orchestrator
    restart: on-failure
  
  video-conferencing-ms-migration:
    image: ${REGISTRY:-localhost:32000}/video-conferencing-ms-example
    build:
      context: ./video-conferencing-ms-example
      dockerfile: Dockerfile
    command: sh -c "sleep 60 && npm run db:migrate"
    environment: *video-variables
    depends_on:
      - postgres
      - postgres_orchestrator
    networks:
      - sandbox
    restart: on-failure

  in-mail-example:
    image: ${REGISTRY:-localhost:32000}/in-mail-example
    build:
      context: ./in-mail-example
      dockerfile: Dockerfile
    ports:
      - "3033:3000"
    networks:
      - sandbox
    environment: *in-mail-variables
    depends_on:
      - postgres
      - postgres_orchestrator
    restart: on-failure

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    networks:
      - sandbox

  camunda:
    container_name: camunda_engine
    image: camunda/camunda-bpm-platform:run-latest
    ports:
      - "8080:8080"
    networks:
      - sandbox
    restart: always

  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - sandbox
    restart: always

  postgres_orchestrator:
    container_name: postgres_orchestrator
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      PGDATA: /data/postgres
      PGPASSWORD: ${POSTGRES_PASSWORD:-changeme}
    ports:
      - "5433:5433"
    networks:
      - sandbox
    depends_on:
      - postgres
    command:
      bash -c "export PGPASSWORD=${POSTGRES_PASSWORD:-changeme}; sleep 30;
               psql -U ${POSTGRES_USER:-postgres} -d postgres -h postgres -c 'create database authentication_db' 2>&1;
               psql -U ${POSTGRES_USER:-postgres} -d postgres -h postgres -c 'create database notification_db' 2>&1;
               psql -U ${POSTGRES_USER:-postgres} -d postgres -h postgres -c 'create database workflow_db' 2>&1;
               psql -U ${POSTGRES_USER:-postgres} -d postgres -h postgres -c 'create database audit_db' 2>&1;
               psql -U ${POSTGRES_USER:-postgres} -d postgres -h postgres -c 'create database scheduler_db' 2>&1;
               psql -U ${POSTGRES_USER:-postgres} -d postgres -h postgres -c 'create database in_mail_db' 2>&1;
               exit 0"

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
      - pgadmin:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - sandbox
    restart: always

networks:
  sandbox:
    driver: bridge

volumes:
  postgres:
  pgadmin: