pipeline {
    agent any
    //TODO: make parameters for registry
    //TODO: setup webooks/build triggers
    stages {
        stage('Build') {
            steps {
                dir("sandbox"){
                    sh "chmod +x ./ci_build.sh"
                    withCredentials([usernamePassword('credentialsId': 'sf-dockerhub', 'usernameVariable': 'DOCKER_USERNAME', 'passwordVariable': 'DOCKER_PASSWORD')]) {
                        sh "./ci_build.sh sourcefuse"
                    }
                }
            }
        }
    }
}