// Copyright (c) 2023 Sourcefuse Technologies
//
// This software is released under the MIT License.
// https://opensource.org/licenses/MIT
export const enum PermissionKey {
  ViewQuestion = '389',
  UpdateQuestion = '390',
  CreateQuestion = '391',
  DeleteQuestion = '392',
  ViewAnyQuestion = '393',
  UpdateAnyQuestion = '394',
  CreateAnyQuestion = '395',
  DeleteAnyQuestion = '396',

  CreateTemplate = '433',
  ViewTemplate = '434',
  UpdateTemplate = '435',
  DeleteTemplate = '436',
  CreateAnyTemplate = '437',
  ViewAnyTemplate = '438',
  UpdateAnyTemplate = '439',
  DeleteAnyTemplate = '440',

  ViewAnyOption = '541',
  UpdateAnyOption = '542',
  CreateAnyOption = '543',
  DeleteAnyOption = '544',
  ViewOption = '421',
  UpdateOption = '422',
  CreateOption = '423',
  DeleteOption = '424',

  CreateTemplateQuestion = '449',
  ViewTemplateQuestion = '450',
  UpdateTemplateQuestion = '451',
  DeleteTemplateQuestion = '452',
  CreateAnyTemplateQuestion = '453',
  ViewAnyTemplateQuestion = '454',
  UpdateAnyTemplateQuestion = '455',
  DeleteAnyTemplateQuestion = '456',

  CreateSurvey = '457',
  ViewSurvey = '458',
  UpdateSurvey = '459',
  DeleteSurvey = '460',
  CreateAnySurvey = '461',
  ViewAnySurvey = '462',
  UpdateAnySurvey = '463',
  DeleteAnySurvey = '464',

  ViewOpenSurvey = '533',
  ViewOpenSurveyQuestion = '534',
  ViewOpenSurveySection = '535',
  ViewOpenSurveyResponse = '536',
  CreateOpenSurveyResponse = '537',

  CreateSurveySection = '490',
  ViewSurveySection = '491',
  UpdateSurveySection = '492',
  DeleteSurveySection = '493',
  CreateAnySurveySection = '494',
  ViewAnySurveySection = '495',
  UpdateAnySurveySection = '496',
  DeleteAnySurveySection = '497',

  CreateSurveyCycle = '473',
  ViewSurveyCycle = '474',
  UpdateSurveyCycle = '475',
  DeleteSurveyCycle = '476',
  CreateAnySurveyCycle = '477',
  ViewAnySurveyCycle = '478',
  UpdateAnySurveyCycle = '479',
  DeleteAnySurveyCycle = '480',

  CreateSurveyResponder = '482',
  ViewSurveyResponder = '483',
  UpdateSurveyResponder = '484',
  DeleteSurveyResponder = '485',
  CreateAnySurveyResponder = '486',
  ViewAnySurveyResponder = '487',
  UpdateAnySurveyResponder = '488',
  DeleteAnySurveyResponder = '489',

  CreateResponderReminder = '527',
  CreateSurveyGoingToStartReminder = '528',

  StartSurveyCycle = '515',
  EndSurveyCycle = '516',
  EndSurvey = '517',
  CreateSurveyResponse = '518',
  ViewSurveyResponse = '519',
  CreateAnySurveyResponse = '520',
  ViewAnySurveyResponse = '521',
  ViewWorkgroupBulkUploadHistory = '522',
  ViewAnyWorkgroupBulkUploadHistory = '523',

  ViewSurveyResponseDetail = '531',
  ViewAnySurveyResponseDetail = '532',

  CreateSurveyQuestion = '465',
  ViewSurveyQuestion = '466',
  UpdateSurveyQuestion = '467',
  DeleteSurveyQuestion = '468',
  CreateAnySurveyQuestion = '469',
  ViewAnySurveyQuestion = '470',
  UpdateAnySurveyQuestion = '471',
  DeleteAnySurveyQuestion = '472',
}
