// Copyright (c) 2023 Sourcefuse Technologies
//
// This software is released under the MIT License.
// https://opensource.org/licenses/MIT
export const enum PermissionKey {
  ViewQuestion = '1',
  UpdateQuestion = '2',
  CreateQuestion = '3',
  DeleteQuestion = '4',
  ViewAnyQuestion = '5',
  UpdateAnyQuestion = '6',
  CreateAnyQuestion = '7',
  DeleteAnyQuestion = '8',

  CreateTemplate = '9',
  ViewTemplate = '10',
  UpdateTemplate = '11',
  DeleteTemplate = '12',
  CreateAnyTemplate = '13',
  ViewAnyTemplate = '14',
  UpdateAnyTemplate = '15',
  DeleteAnyTemplate = '16',

  ViewAnyOption = '17',
  UpdateAnyOption = '18',
  CreateAnyOption = '19',
  DeleteAnyOption = '20',
  ViewOption = '21',
  UpdateOption = '22',
  CreateOption = '23',
  DeleteOption = '24',

  CreateTemplateQuestion = '25',
  ViewTemplateQuestion = '26',
  UpdateTemplateQuestion = '27',
  DeleteTemplateQuestion = '28',
  CreateAnyTemplateQuestion = '29',
  ViewAnyTemplateQuestion = '30',
  UpdateAnyTemplateQuestion = '31',
  DeleteAnyTemplateQuestion = '32',

  CreateSurvey = '33',
  ViewSurvey = '34',
  UpdateSurvey = '35',
  DeleteSurvey = '36',
  CreateAnySurvey = '37',
  ViewAnySurvey = '38',
  UpdateAnySurvey = '39',
  DeleteAnySurvey = '40',

  ViewOpenSurvey = '41',
  ViewOpenSurveyQuestion = '42',
  ViewOpenSurveySection = '43',
  ViewOpenSurveyResponse = '44',
  CreateOpenSurveyResponse = '45',

  CreateSurveySection = '46',
  ViewSurveySection = '47',
  UpdateSurveySection = '48',
  DeleteSurveySection = '49',
  CreateAnySurveySection = '50',
  ViewAnySurveySection = '51',
  UpdateAnySurveySection = '52',
  DeleteAnySurveySection = '53',

  CreateSurveyCycle = '54',
  ViewSurveyCycle = '55',
  UpdateSurveyCycle = '56',
  DeleteSurveyCycle = '57',
  CreateAnySurveyCycle = '58',
  ViewAnySurveyCycle = '59',
  UpdateAnySurveyCycle = '60',
  DeleteAnySurveyCycle = '61',

  CreateSurveyResponder = '62',
  ViewSurveyResponder = '63',
  UpdateSurveyResponder = '64',
  DeleteSurveyResponder = '65',
  CreateAnySurveyResponder = '66',
  ViewAnySurveyResponder = '67',
  UpdateAnySurveyResponder = '68',
  DeleteAnySurveyResponder = '69',

  CreateResponderReminder = '70',
  CreateSurveyGoingToStartReminder = '71',

  StartSurveyCycle = '72',
  EndSurveyCycle = '73',
  EndSurvey = '74',
  CreateSurveyResponse = '75',
  ViewSurveyResponse = '76',
  CreateAnySurveyResponse = '77',
  ViewAnySurveyResponse = '78',
  ViewWorkgroupBulkUploadHistory = '79',
  ViewAnyWorkgroupBulkUploadHistory = '80',

  ViewSurveyResponseDetail = '81',
  ViewAnySurveyResponseDetail = '82',

  CreateSurveyQuestion = '83',
  ViewSurveyQuestion = '84',
  UpdateSurveyQuestion = '85',
  DeleteSurveyQuestion = '86',
  CreateAnySurveyQuestion = '87',
  ViewAnySurveyQuestion = '88',
  UpdateAnySurveyQuestion = '89',
  DeleteAnySurveyQuestion = '90',
}
