# Path to sources
sonar.sources=.
sonar.exclusions=api-docs/**,**/dist/**,packages/cli/src/generators/microservice/templates/Dockerfile*,packages/cli/src/generators/scaffold/templates/Dockerfile.deps,packages/cli/src/generators/scaffold/templates/scripts/**
#sonar.inclusions=packages/**/src/**

# Path to tests
sonar.tests=.
#sonar.test.exclusions=
sonar.test.inclusions=packages/**/src/__tests__/**

# Source encoding
sonar.sourceEncoding=UTF-8

# Exclusions for copy-paste detection
#sonar.cpd.exclusions=
