apiVersion: v1
kind: Service
metadata:
  labels:
    io.sourceloop.service: scheduler-example
  name: scheduler-example
spec:
  ports:
    - name: "3000"
      port: 3000
      targetPort: 3000
  selector:
    io.sourceloop.service: scheduler-example
status:
  loadBalancer: {}
