// Copyright (c) 2023 Sourcefuse Technologies
//
// This software is released under the MIT License.
// https://opensource.org/licenses/MIT
export const enum PermissionKey {
  GetSubscriptionCount = 'GetSubscriptionCount',
  CreateSubscription = 'CreateSubscription',
  GetSubscriptions = 'GetSubscriptions',
  UpdateSubscriptions = 'UpdateSubscriptions',
  DeleteSubscriptions = 'DeleteSubscriptions',
  CreateOrder = 'CreateOrder',
  ViewOrder = 'ViewOrder',
  UpdateOrder = 'UpdateOrder',
  DeleteOrder = 'DeleteOrder',
  CreateGateway = 'CreateGateway',
  UpdateGateway = 'UpdateGateway',
  ViewGateway = 'ViewGateway',
  DeleteGateway = 'DeleteGateway',
  CreateTemplate = 'CreateTemplate',
  UpdateTemplate = 'UpdateTemplate',
  ViewTemplate = 'ViewTemplate',
  DeleteTemplate = 'DeleteTemplate',
  CreateTransaction = 'CreateTransaction',
  ViewTransaction = 'ViewTransaction',
  UpdateTransaction = 'UpdateTransaction',
  DeleteTransaction = 'DeleteTransaction',
  CreateRefund = 'CreateRefund',
  GetSubscriptionCountNum = '1',
  CreateSubscriptionNum = '2',
  GetSubscriptionsNum = '3',
  UpdateSubscriptionsNum = '4',
  DeleteSubscriptionsNum = '5',
  CreateOrderNum = '6',
  ViewOrderNum = '7',
  UpdateOrderNum = '8',
  DeleteOrderNum = '9',
  CreateGatewayNum = '10',
  UpdateGatewayNum = '11',
  ViewGatewayNum = '12',
  DeleteGatewayNum = '13',
  CreateTemplateNum = '14',
  UpdateTemplateNum = '15',
  ViewTemplateNum = '16',
  DeleteTemplateNum = '17',
  CreateTransactionNum = '18',
  ViewTransactionNum = '19',
  UpdateTransactionNum = '20',
  DeleteTransactionNum = '21',
  CreateRefundNum = 'CreateRefundNum',
}
