apiVersion: v1
kind: Service
metadata:
  labels:
    io.sourceloop.service: redis
  name: redis
spec:
  ports:
    - name: "6379"
      port: 6379
      targetPort: 6379
  selector:
    io.sourceloop.service: redis
status:
  loadBalancer: {}
