apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.sourceloop.service: redis
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      io.sourceloop.service: redis
  strategy: {}
  template:
    metadata:
      labels:
#        network/sourceloop-sanbox: "true"
        io.sourceloop.service: redis
    spec:
      containers:
        - image: redis:alpine
          name: redis
          ports:
            - containerPort: 6379
          resources: {}
      restartPolicy: Always
status: {}
