apiVersion: apps/v1
kind: Deployment
metadata:
  name: health-check
  namespace: sourceloop-sandbox
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
