ALTER TABLE auth_clients
ADD IF NOT EXISTS created_by VARCHAR(100),
ADD IF NOT EXISTS modified_by VARCHAR(100);

ALTER TABLE user_credentials
ADD IF NOT EXISTS created_by VARCHAR(100),
ADD IF NOT EXISTS modified_by VARCHAR(100);

ALTER TABLE user_tenants
ADD IF NOT EXISTS created_by VARCHAR(100),
ADD IF NOT EXISTS modified_by VARCHAR(100);
