apiVersion: v1
kind: Service
metadata:
  labels:
    io.sourceloop.service: notification-socket-example
  name: notification-socket-example
  namespace: sourceloop-sandbox
spec:
  ports:
    - name: "3000"
      port: 3000
      targetPort: 3000
  selector:
    io.sourceloop.service: notification-socket-example
status:
  loadBalancer: {}
