import * as jwt from 'jsonwebtoken';
import {PermissionKey} from '../../enum';
//User Creds
const User = {
  id: 1,
  username: 'test_user',
  password: 'test_password',
};
export const testUserPayload = {
  ...User,
  role: 1,
  authClientId: 2,
  authClientIds: [2],
  deleted: false,
  userLocked: false,
  permissions: [
    PermissionKey.CreateQuestion,
    PermissionKey.CreateAnyQuestion,
    PermissionKey.ViewQuestion,
    PermissionKey.ViewAnyQuestion,
    PermissionKey.UpdateQuestion,
    PermissionKey.UpdateAnyQuestion,
    PermissionKey.DeleteQuestion,
    PermissionKey.DeleteAnyQuestion,
    PermissionKey.CreateOption,
    PermissionKey.CreateAnyOption,
    PermissionKey.ViewOption,
    PermissionKey.ViewAnyOption,
    PermissionKey.UpdateOption,
    PermissionKey.UpdateAnyOption,
    PermissionKey.ViewOption,
    PermissionKey.ViewAnyOption,
    PermissionKey.DeleteAnyOption,
    PermissionKey.DeleteOption,
    PermissionKey.CreateTemplate,
    PermissionKey.ViewTemplate,
    PermissionKey.UpdateTemplate,
    PermissionKey.DeleteTemplate,
    PermissionKey.CreateAnyTemplate,
    PermissionKey.ViewAnyTemplate,
    PermissionKey.UpdateAnyTemplate,
    PermissionKey.DeleteAnyTemplate,
    PermissionKey.CreateTemplateQuestion,
    PermissionKey.ViewTemplateQuestion,
    PermissionKey.UpdateTemplateQuestion,
    PermissionKey.DeleteTemplateQuestion,
    PermissionKey.CreateAnyTemplateQuestion,
    PermissionKey.ViewAnyTemplateQuestion,
    PermissionKey.UpdateAnyTemplateQuestion,
    PermissionKey.DeleteAnyTemplateQuestion,
    PermissionKey.CreateSurvey,
    PermissionKey.CreateAnySurvey,
    PermissionKey.ViewSurvey,
    PermissionKey.ViewAnySurvey,
    PermissionKey.UpdateAnySurvey,
    PermissionKey.UpdateSurvey,
    PermissionKey.ViewOpenSurvey,
    PermissionKey.DeleteSurvey,
    PermissionKey.DeleteAnySurvey,
    PermissionKey.ViewAnySurveyQuestion,
    PermissionKey.ViewSurveyQuestion,
    PermissionKey.UpdateAnySurveyQuestion,
    PermissionKey.UpdateSurveyQuestion,
    PermissionKey.CreateSurveyQuestion,
    PermissionKey.CreateAnySurveyQuestion,
    PermissionKey.DeleteSurveyQuestion,
    PermissionKey.DeleteAnySurveyQuestion,
    PermissionKey.CreateSurveyCycle,
    PermissionKey.CreateAnySurveyCycle,
    PermissionKey.ViewSurveyCycle,
    PermissionKey.ViewAnySurveyCycle,
    PermissionKey.DeleteSurveyCycle,
    PermissionKey.DeleteAnySurveyCycle,
    PermissionKey.UpdateAnySurveyCycle,
    PermissionKey.UpdateSurveyCycle,
    PermissionKey.CreateSurveyResponder,
    PermissionKey.CreateAnySurveyResponder,
    PermissionKey.CreateResponderReminder,
    PermissionKey.ViewSurveyResponder,
    PermissionKey.ViewAnySurveyResponder,
    PermissionKey.UpdateAnySurveyResponder,
    PermissionKey.UpdateSurveyResponder,
    PermissionKey.DeleteSurveyResponder,
    PermissionKey.DeleteAnySurveyResponder,
    PermissionKey.CreateSurveySection,
    PermissionKey.CreateAnySurveySection,
    PermissionKey.ViewSurveySection,
    PermissionKey.ViewAnySurveySection,
    PermissionKey.ViewOpenSurveySection,
    PermissionKey.UpdateAnySurveySection,
    PermissionKey.UpdateSurveySection,
    PermissionKey.DeleteSurveySection,
    PermissionKey.DeleteAnySurveySection,
    PermissionKey.ViewSurveyResponse,
    PermissionKey.ViewAnySurveyResponse,
    PermissionKey.ViewOpenSurveyResponse,
    PermissionKey.CreateSurveyResponse,
    PermissionKey.CreateAnySurveyResponse,
    PermissionKey.CreateOpenSurveyResponse,
  ],
};
export const token = jwt.sign(testUserPayload, 'kdskssdkdfs', {
  expiresIn: 180000,
  issuer: 'sf',
});
