apiVersion: v1
kind: Pod
metadata:
  labels:
#    network/sourceloop-sanbox: "true"
    io.sourceloop.service: audit-ms-migration
  name: audit-ms-migration
  namespace: sourceloop-sandbox
spec:
  containers:
    - args:
        - sh
        - -c
        - sleep 60 && npm run db:migrate
      env:
        - name: DB_DATABASE
          value: audit_db
        - name: DB_HOST
          value: postgres.sourceloop-sandbox.svc.cluster.local
        - name: DB_PASSWORD
          value: changeme
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: postgres
        - name: JWT_ISSUER
          value: https://loopback4-microservice-catalog
        - name: JWT_SECRET
          value: i_am_a_strong_secret
        - name: LOG_LEVEL
          value: debug
        - name: NODE_ENV
          value: dev
        - name: REDIS_DB
          value: "0"
        - name: REDIS_HOST
          value: redis
        - name: REDIS_PASSWORD
          value: test
        - name: REDIS_PORT
          value: "6379"
      image: localhost:32000/audit-ms-example:latest
      name: audit-ms-migration
      resources: {}
  restartPolicy: OnFailure
status: {}
