apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.sourceloop.service: postgres
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      io.sourceloop.service: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
#        network/sourceloop-sanbox: "true"
        io.sourceloop.service: postgres
    spec:
      containers:
        - env:
            - name: PGDATA
              value: /data/postgres
            - name: POSTGRES_PASSWORD
              value: changeme
            - name: POSTGRES_USER
              value: postgres
          image: postgres
          name: postgres-container
          ports:
            - containerPort: 5432
          resources: {}
          volumeMounts:
            - mountPath: /data/postgres
              name: postgres
      restartPolicy: Always
      volumes:
        - name: postgres
          persistentVolumeClaim:
            claimName: postgres
status: {}
