DROP TABLE "main".assignees CASCADE;
DROP TABLE "main".tasks CASCADE;
DROP TABLE "main".task_assignements CASCADE;
DROP TABLE "main".task_workflow_mappings CASCADE;
DROP TABLE "main".activities CASCADE;
DROP TABLE "main".activity_events CASCADE;
DROP TABLE "main".events CASCADE;
DROP TABLE "main".event_workflow_mapping CASCADE;
DROP TABLE "main".webhook_subscriptions CASCADE;