export enum PermissionsEnums {
  ComposeMail = 'ComposeMail',
  UpdateMail = 'UpdateMail',
  ReplyMail = 'ReplyMail',
  AddAttachments = 'AddAttachments',
  GetThreads = 'GetThreads',
  GetThread = 'GetThread',
  GetInMails = 'GetInMails',
  GetInMail = 'GetInMail',
  TrashMail = 'TrashMail',
  RestoreMail = 'RestoreMail',
  GetInMailAttachments = 'GetInMailAttachments',
  GetMetadata = 'GetMetadata',
  DeleteAttachment = 'DeleteAttachment',
}
