// Copyright (c) 2022 Sourcefuse Technologies
//
// This software is released under the MIT License.
// https://opensource.org/licenses/MIT
export const enum PermissionKey {
  CreateUserGroup = 'CreateUserGroup',
  ViewUserGroupList = 'ViewUserGroupList',
  UpdateUserGroup = 'UpdateUserGroup',
  DeleteUserGroup = 'DeleteUserGroup',
  DeleteSubscriptions = 'DeleteSubscriptions',
  ViewRoles = 'ViewRoles',
  NotAllowed = 'NotAllowed',
  CreateRoles = 'CreateRoles',
  UpdateRoles = 'UpdateRoles',
  DeleteRoles = 'DeleteRoles',
  ViewAnyUser = 'ViewAnyUser',
  ViewTenantUser = 'ViewTenantUser',
  ViewTenantUserRestricted = 'ViewTenantUserRestricted',
  ViewAllUser = 'ViewAllUser',
  ViewOwnUser = 'ViewOwnUser',
  CreateAnyUser = 'CreateAnyUser',
  CreateTenantUser = 'CreateTenantUser',
  CreateTenantUserRestricted = 'CreateTenantUserRestricted',
  UpdateAnyUser = 'UpdateAnyUser',
  UpdateOwnUser = 'UpdateOwnUser',
  UpdateTenantUser = 'UpdateTenantUser',
  UpdateTenantUserRestricted = 'UpdateTenantUserRestricted',
  DeleteAnyUser = 'DeleteAnyUser',
  DeleteTenantUser = 'DeleteTenantUser',
  DeleteTenantUserRestricted = 'DeleteTenantUserRestricted',
  CreateTenant = 'CreateTenant',
  ViewTenant = 'ViewTenant',
  UpdateTenant = 'UpdateTenant',
  ViewOwnTenant = 'ViewOwnTenant',
  UpdateOwnTenant = 'UpdateOwnTenant',
  DeleteTenant = 'DeleteTenant',
  AddMemberToUserGroup = 'AddMemberToUserGroup',
  UpdateMemberInUserGroup = 'UpdateMemberInUserGroup',
  RemoveMemberFromUserGroup = 'RemoveMemberFromUserGroup',
  LeaveUserGroup = 'LeaveUserGroup',
  UpdateUserTenantPreference = 'UpdateUserTenantPreference',
  ViewUserTenantPreference = 'ViewUserTenantPreference',
}
